### PR TITLE
Support spaces and line breaks

### PR DESCRIPTION
**Pull request by greendrake**
Neither spaces nor line breaks work for me without this fix.

### CODE REVIEW

**Comment by JeffBrockStudio** [comment]
I'm really grateful for your fix -- it works for me, and it saved a critical project I'm working on.

**Comment by kartsims** [comment]
sorry it hadn't been merged before

I just don't do PHP anymore, but thanks a lot @greendrake for this PR, I'll merge it rn 🙌

**Comment by JeffBrockStudio** [comment]
Simon, THANK YOU for this fantastic library! I'm working with a university to build a logo generator tool, so that all their departments won't have to send manual requests to the marketing department. I had tried embedding the font into the generated SVGs with another library, but the results were bloated files that would break when viewed in Adobe Illustrator. Your library is the perfect solution.

**Comment by kartsims** [comment]
Thanks Jeff for the kind words <3

**Comment by Ambient-Impact** [comment]
@kartsims I'm also using this on my own site - specifically the project titles on [my portfolio](https://ambientimpact.com/portfolio) that are intended to look like they're cut out of paper along the top of the thumbnails - and it's wonderful to be able to automagically generate an SVG from the heading text so I can actually align the bottom of those letters with the block they sit on. Thanks for this!

**Pull request merged**
